### ISSUE TITLE
Does it support getting help from docstring instead of explicit attribute?

### ISSUE THREAD

**Issue by vi** [murarth/gumdrop#16]
Crate-level documentation is all about

```
#[options(help = "help text")]
item: Type,
```

, but I don't see occurence of

```
/// help text
#[options]
item: Type
```

Is it supposered? If yes, some of documentation examples should use it.

**Comment by murarth** [comment]
This is not currently supported, but I think it's a good idea. I will see about implementing it soon.

**Comment by awygle** [comment]
I'd also like to see a way to add a top-level description of the program, maybe as an #[option(help = "..")] attribute on the type.

**Comment by murarth** [comment]
I've just pushed a commit to use doc comments as `help` values. It also adds `help` attribute/doc comment for `derive(Options)` on `struct` types.

Thank you, @vi, for this issue.
And thank you, @awygle, for that additional suggestion.

**Comment by vi** [comment]
If there are both `help="` and the docstring, does the attribute take precedence?

**Comment by murarth** [comment]
@vi: Yes.
