### ISSUE TITLE
Allow help flag to be specified without required arguments

### ISSUE THREAD

**Issue by awygle** [murarth/gumdrop#17]
Commonly programs allow specifying `--help` with no other arguments, even if those other arguments would be "required" otherwise. This isn't true in gumdrop today, or at least it isn't working for me.

**Comment by murarth** [comment]
This totally makes sense. I just hadn't thought of it before.

I've just pushed a commit that resolves this. Thanks for the issue.

**Comment by liamdawson** [comment]
I just encountered this one too--do you plan to release the change soon? I'll use the source as git in the meantime 🙂

**Comment by murarth** [comment]
@liamdawson I will generally publish a new version when I need it or when someone asks, but I do like to wait a bit after introducing a new feature, to see if any bugs come out of the new code. If I haven't published a new release in a week, remind me again and I'll most likely make one.

**Comment by awygle** [comment]
@murarth could we have that new release now, please? :D

**Comment by murarth** [comment]
Oops. It's been quite a bit more than a week, hasn't it?

I've just published version 0.6.0 to crates.io.
