### ISSUE TITLE
support for different verbosity levels: -v -vv -vvv -vvvv

### ISSUE THREAD

**Issue by fretn** [murarth/gumdrop#23]
It would be nice if gumdrop would support `-v` `-vv` `-vvv` `-vvvv` as input for setting the verbosity level

**Comment by murarth** [comment]
This is already supported, using the `#[options(count)]` attribute:

https://github.com/murarth/gumdrop/blob/9e457a78af082dfce09a93738922c000ad5b5a6a/tests/options.rs#L334-L347

**Comment by fretn** [comment]
sorry for wasting your time 🤦‍♂

**Comment by drmason13** [comment]
Might be worth a quick example add this is a common use case for `#[options(count)]`?

I'd be interested in adding an example to the docs (or possibly the README)

**Comment by murarth** [comment]
@drmason13 There is an example of `options(count)` in the lib docs:
https://github.com/murarth/gumdrop/blob/9cbeb6275c7f24be67094b4e6c7f43330ab0d013/src/lib.rs#L41-L44
