### ISSUE TITLE
Add the 'required' option to the documentation

### ISSUE THREAD

**Issue by RazrFalcon** [murarth/gumdrop#24]
Currently, it doesn't mentioned anywhere.

And it will be nice to have a list of all possible options/attributes.

**Comment by murarth** [comment]
Full documentation of the `#[options(...)]` attribute is available in the docs for [`gumdrop_derive`](https://docs.rs/crate/gumdrop_derive/).

I've added a link in the crate-level docs for `gumdrop` that points to the `gumdrop_derive` docs.
