### ISSUE TITLE
Use bullet points in gumdrop_derive docs

### ISSUE THREAD

**Issue by ssokolow** [murarth/gumdrop#31]
Currently, the [gumdrop_derive docs](https://docs.rs/crate/gumdrop_derive/) on docs.rs look like this:

![Screenshot_2020-06-13 gumdrop_derive 0 8 0 - Docs rs](https://user-images.githubusercontent.com/46915/84559925-90f07500-ad2e-11ea-9ac6-d9e3b773c2f0.png)

...which makes it needlessly difficult to read them. The simplest solution is to add some bullet points.

**Comment by murarth** [comment]
It is using bullet points: https://github.com/murarth/gumdrop/blob/c4198f00096016aadbf92929b2d6d5cedad0d322/gumdrop_derive/src/lib.rs#L16-L18

For some reason, docs.rs is applying `list-style: none` to list elements.

**Comment by ssokolow** [comment]
Ahh. Sorry about that. Docs.rs getting something so simple wrong and not getting called on it ages ago by some other crate publisher seemed like such an unbelievable possibility that I dismissed it without checking.

I'll check for a bug on their tracker when I have a few minutes.
