### ISSUE TITLE
`help` magic option is undocumented?

### ISSUE THREAD

**Issue by icefoxen** [murarth/gumdrop#36]
As far as I can tell, if you put a `help` option in your options struct, `gumdrop` magically notices it and adds behavior to print out a help messages for you.  Also as far as I can tell, nowhere in the docs or examples does it actually talk about this.

**Comment by murarth** [comment]
I've submitted PR #37 to address this issue.
The documentation is added to the example in `src/lib.rs`. I hope the wording is clear and concise. Please let me know what you think.
